version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://admin:Postgres@forever12@db:5432/hbsp
      - BETTER_AUTH_SECRET=8YJbsDbmGnnCWwTaLkf9na0fNauWVoNW
      - BETTER_AUTH_URL=http://localhost:3000
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next

  db:
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Postgres@forever12
      - POSTGRES_DB=hbsp
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
