import type { Metadata } from "next";
import { Geist_Mono, Sunflower } from "next/font/google";
import "./globals.css";
import React from "react";
import ReduxStoreProvider from "@/components/providers/redux-store-provider";
import { Toaster } from "@/components/atoms/sonner";

const geistSans = Sunflower({
  variable: "--font-sunflower",
  weight: ["300", "500", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReduxStoreProvider user={null}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased font-sans`}
        >
          {children}
          <Toaster />
        </body>
      </ReduxStoreProvider>
    </html>
  );
}
